root: required
language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t gowithkk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kailiu/react-test npm test

after_success:
  - docker build -t gowithkk/multi-client ./client
  - docker build -t gowithkk/multi-nginx ./nginx
  - docker build -t gowithkk/multi-server ./server
  - docker build -t gowithkk/multi-worker ./worker
  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push gowithkk/multi-client
  - docker push gowithkk/multi-nginx
  - docker push gowithkk/multi-server
  - docker push gowithkk/multi-worker